services:
  bot:
    image: ghcr.io/johnnybui/okos
    container_name: okos
    env_file: .env.docker
    environment:
      - PORT=11435
    ports:
      - '11435:11435'
    depends_on:
      - redis
    restart: unless-stopped
    networks:
      - okos-network

  redis:
    image: redis
    container_name: okos-redis
    volumes:
      - ./redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - okos-network

networks:
  okos-network:
    driver: bridge
