services:
  bot:
    build: .
    container_name: okos
    env_file: .env
    environment:
      - REDIS_URL=redis://okos-redis:6379
      - OLLAMA_API_URL=http://okos-ollama:11434
    depends_on:
      - okos-redis
      - okos-ollama
    restart: unless-stopped
    networks:
      - okos-network

  okos-redis:
    image: redis
    container_name: okos-redis
    ports:
      - '6479:6379'
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - okos-network

  okos-ollama:
    image: ollama/ollama
    container_name: okos-ollama
    ports:
      - '12434:11434'
    volumes:
      - ollama-data:/root/.ollama
    restart: unless-stopped
    networks:
      - okos-network
    devices:
      - /dev/dri:/dev/dri

volumes:
  redis-data:
  ollama-data:

networks:
  okos-network:
    driver: bridge
